version: '3'

services:
    grpcserver:
        build: 
            context: ./gRPCserver
            args:
                NODE_ENV: development
        volumes:
            - ./gRPCserver:/app
            - /app/node_modules
            - ./protos:/app/protos
        environment:
            - PORT=50051
            - MYSQL_IP=mysql_db
            - MYSQL_PROT=3306
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
    grpcclient:
        ports: 
            - "3000:3000"
        volumes:
            - ./gRPCclient:/app
            - /app/node_modules
            - ./protos:/app/protos
        environment:
            - PORT=3000
    mysql_db:
        command: --init-file /data/application/init.sql    
        volumes:
            - ./databasedumps/init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: 'password'        


    mysql_admin:
        image: phpmyadmin:5.1
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql_db
            PMA_PASSWORD: 'password'
        depends_on:
            - mysql_db