version: '3'

services:
    grpcserver:
        build: 
            context: ./gRPCserver
            args:
                NODE_ENV: development
        ports: 
            - "50051:50051"
        volumes:
            - ./gRPCserver:/app
            - /app/node_modules
            - ./protos:/app/protos
        environment:
            - PORT=50051
            - MYSQL_IP=mysql_db
            - MYSQL_PROT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_DB=literature
    grpcservergo:
        ports: 
            - "50052:50052"
        volumes:
            - ./gRPCserver_go:/app
        environment:
            - PORT=50052
            - MYSQL_IP=mysql_db
            - MYSQL_PROT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_DB=literature
        command: go run main.go
    grpcclient:
        ports: 
            - "3000:3000"
        volumes:
            - ./gRPCclient:/app
            - /app/node_modules
            - ./protos:/app/protos
        environment:
            - PORT=3000
    mysql_db:
        environment:
            MYSQL_ROOT_PASSWORD: 'password'        


    mysql_admin:
        image: phpmyadmin:5.1
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql_db
            PMA_PASSWORD: 'password'
        depends_on:
            - mysql_db