version: '3'

services:
    grpcserver:
        build: 
            context: ./gRPCserver
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
            - PORT=50051
            - MYSQL_IP=mysql_db
            - MYSQL_PROT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        command: node index.js
    grpcclient:
        build: ./gRPCclient
        environment:
            - PORT=3000
        command: node index.js
    mysql_db:
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
volumes:
    mysql-db: