version: '3'

services:
    grpcserver:
        build: 
            context: ./gRPCserver
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
            - PORT=50051
            - MYSQL_IP=${MYSQL_IP}
            - MYSQL_PROT=${MYSQL_PROT}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DB=${MYSQL_DB}
        command: node index.js
    grpcclient:
        build: ./gRPCclient
        environment:
            - PORT=3000
        command: node index.js
    mysql_db:
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
volumes:
    mysql-db: