version: '3'

services:
    grpcserver:
        build: ./gRPCserver
        image: edwang09/grpc-node-server
        depends_on:
            - mysql_db
    grpcservergo:
        build: ./gRPCserver_go
        # image: edwang09/grpc-node-server-go
        depends_on:
            - mysql_db
    grpcclient:
        build: ./gRPCclient
        image: edwang09/grpc-node-client
        ports: 
            - "80:3000"
    mysql_db:
        image: mysql:5.7
        restart: always
        command: --init-file /data/application/init.sql    
        volumes:
            - ./database/init.sql:/data/application/init.sql
            - mysql-db:/var/lib/mysql
volumes:
    mysql-db: